#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db08")]
	public partial class cnDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertcn_ipc(cn_ipc instance);
    partial void Updatecn_ipc(cn_ipc instance);
    partial void Deletecn_ipc(cn_ipc instance);
    partial void Insertcn_zt(cn_zt instance);
    partial void Updatecn_zt(cn_zt instance);
    partial void Deletecn_zt(cn_zt instance);
    #endregion
		
		public cnDataContext() : 
				base(global::BRDB.Properties.Settings.Default.db08ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public cnDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cnDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cn_ipc> cn_ipc
		{
			get
			{
				return this.GetTable<cn_ipc>();
			}
		}
		
		public System.Data.Linq.Table<cn_zt> cn_zt
		{
			get
			{
				return this.GetTable<cn_zt>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cn_ipc")]
	public partial class cn_ipc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _an;
		
		private string _ipc;
		
		private System.Nullable<char> _ipc1;
		
		private string _ipc3;
		
		private string _ipc4;
		
		private string _ipc7;
		
		private System.Nullable<int> _sort;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnanChanging(string value);
    partial void OnanChanged();
    partial void OnipcChanging(string value);
    partial void OnipcChanged();
    partial void Onipc1Changing(System.Nullable<char> value);
    partial void Onipc1Changed();
    partial void Onipc3Changing(string value);
    partial void Onipc3Changed();
    partial void Onipc4Changing(string value);
    partial void Onipc4Changed();
    partial void Onipc7Changing(string value);
    partial void Onipc7Changed();
    partial void OnsortChanging(System.Nullable<int> value);
    partial void OnsortChanged();
    #endregion
		
		public cn_ipc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an", DbType="VarChar(13)")]
		public string an
		{
			get
			{
				return this._an;
			}
			set
			{
				if ((this._an != value))
				{
					this.OnanChanging(value);
					this.SendPropertyChanging();
					this._an = value;
					this.SendPropertyChanged("an");
					this.OnanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipc", DbType="VarChar(15)")]
		public string ipc
		{
			get
			{
				return this._ipc;
			}
			set
			{
				if ((this._ipc != value))
				{
					this.OnipcChanging(value);
					this.SendPropertyChanging();
					this._ipc = value;
					this.SendPropertyChanged("ipc");
					this.OnipcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipc1", DbType="Char(1)")]
		public System.Nullable<char> ipc1
		{
			get
			{
				return this._ipc1;
			}
			set
			{
				if ((this._ipc1 != value))
				{
					this.Onipc1Changing(value);
					this.SendPropertyChanging();
					this._ipc1 = value;
					this.SendPropertyChanged("ipc1");
					this.Onipc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipc3", DbType="VarChar(3)")]
		public string ipc3
		{
			get
			{
				return this._ipc3;
			}
			set
			{
				if ((this._ipc3 != value))
				{
					this.Onipc3Changing(value);
					this.SendPropertyChanging();
					this._ipc3 = value;
					this.SendPropertyChanged("ipc3");
					this.Onipc3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipc4", DbType="VarChar(5)")]
		public string ipc4
		{
			get
			{
				return this._ipc4;
			}
			set
			{
				if ((this._ipc4 != value))
				{
					this.Onipc4Changing(value);
					this.SendPropertyChanging();
					this._ipc4 = value;
					this.SendPropertyChanged("ipc4");
					this.Onipc4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipc7", DbType="VarChar(7)")]
		public string ipc7
		{
			get
			{
				return this._ipc7;
			}
			set
			{
				if ((this._ipc7 != value))
				{
					this.Onipc7Changing(value);
					this.SendPropertyChanging();
					this._ipc7 = value;
					this.SendPropertyChanged("ipc7");
					this.Onipc7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort", DbType="Int")]
		public System.Nullable<int> sort
		{
			get
			{
				return this._sort;
			}
			set
			{
				if ((this._sort != value))
				{
					this.OnsortChanging(value);
					this.SendPropertyChanging();
					this._sort = value;
					this.SendPropertyChanged("sort");
					this.OnsortChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cn_zt")]
	public partial class cn_zt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _an;
		
		private int _zt;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnanChanging(string value);
    partial void OnanChanged();
    partial void OnztChanging(int value);
    partial void OnztChanged();
    #endregion
		
		public cn_zt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_an", DbType="VarChar(13)")]
		public string an
		{
			get
			{
				return this._an;
			}
			set
			{
				if ((this._an != value))
				{
					this.OnanChanging(value);
					this.SendPropertyChanging();
					this._an = value;
					this.SendPropertyChanged("an");
					this.OnanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zt", DbType="Int NOT NULL")]
		public int zt
		{
			get
			{
				return this._zt;
			}
			set
			{
				if ((this._zt != value))
				{
					this.OnztChanging(value);
					this.SendPropertyChanging();
					this._zt = value;
					this.SendPropertyChanged("zt");
					this.OnztChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
